- hosts: all
  become: true
  tasks:
    - name: Delete old deployment (ignore error if not present)
      shell: KUBECONFIG=/home/ubuntu/.kube/config kubectl delete -f /home/ubuntu/Deployment.yml || true

    - name: Delete old service (ignore error if not present)
      shell: KUBECONFIG=/home/ubuntu/.kube/config kubectl delete -f /home/ubuntu/Service.yml || true

    - name: Apply new deployment
      shell: KUBECONFIG=/home/ubuntu/.kube/config kubectl apply -f /home/ubuntu/Deployment.yml

    - name: Apply new service
      shell: KUBECONFIG=/home/ubuntu/.kube/config kubectl apply -f /home/ubuntu/Service.yml




