- name: Deploy app to EKS
  hosts: k8s
  tasks:
    - name: Configure kubeconfig for EKS
      shell: aws eks update-kubeconfig --region ap-south-1 --name my-eks-cluster

    - name: Delete old deployment
      shell: kubectl delete -f /home/ubuntu/Deployment.yml || true

    - name: Apply new deployment
      shell: kubectl apply -f /home/ubuntu/Deployment.yml

    - name: Apply service
      shell: kubectl apply -f /home/ubuntu/Service.yml


