---
- name: Deploy app to EKS
  hosts: all
  tasks:
    - name: Set KUBECONFIG environment variable
      shell: export KUBECONFIG=/home/ubuntu/.kube/config
      become: true

    - name: Delete old deployment
      shell: kubectl delete -f /home/ubuntu/Deployment.yml || true
      become: true

    - name: Apply new deployment
      shell: kubectl apply -f /home/ubuntu/Deployment.yml
      become: true

    - name: Apply service
      shell: kubectl apply -f /home/ubuntu/Service.yml
      become: true



