- name: Deploy application to Kubernetes node
  hosts: node
  become: true
  tasks:
    - name: Ensure deployment file exists
      copy:
        src: ./Deployment.yml
        dest: /home/ubuntu/Deployment.yml

    - name: Delete old deployment (ignore error if not exists)
      shell: |
        kubectl delete -f /home/ubuntu/Deployment.yml --kubeconfig /home/ubuntu/.kube/config || true

    - name: Apply new deployment
      shell: |
        kubectl apply -f /home/ubuntu/Deployment.yml --kubeconfig /home/ubuntu/.kube/config



